VPOS_ERRORS = {
    "0000": "Başarılı",
    "0001": "BANKANIZI ARAYIN",
    "0002": "BANKANIZI ARAYIN",
    "0003": "ÜYE KODU HATALI/TANIMSIZ",
    "0004": "KARTA EL KOYUNUZ",
    "0005": "İŞLEM ONAYLANMADI.",
    "0006": "HATALI İŞLEM",
    "0007": "KARTA EL KOYUNUZ",
    "0009": "TEKRAR DENEYİNİZ",
    "0010": "TEKRAR DENEYİNİZ",
    "0011": "TEKRAR DENEYİNİZ",
    "0012": "Geçersiz İşlem",
    "0013": "Geçersiz İşlem Tutarı",
    "0014": "Geçersiz Kart Numarası",
    "0015": "MÜŞTERİ YOK/BIN HATALI",
    "0021": "İŞLEM ONAYLANMADI",
    "0030": "MESAJ FORMATI HATALI (ÜYE İŞYERİ)",
    "0032": "DOSYASINA ULAŞILAMADI",
    "0033": "SÜRESİ BİTMİŞ/İPTAL KART",
    "0034": "SAHTE KART",
    "0036": "İŞLEM ONAYLANMADI",
    "0038": "ŞİFRE AŞIMI/KARTA EL KOY 0041 KAYIP KART- KARTA EL KOY 0043 ÇALINTI KART-KARTA EL KOY",
    "0051": "LIMIT YETERSIZ",
    "0052": "HESAP NOYU KONTROL EDİN",
    "0053": "HESAP YOK",
    "0054": "VADE SONU GEÇMİŞ KART",
    "0055": "Hatalı Kart Şifresi",
    "0056": "Kart Tanımlı Değil.",
    "0057": "KARTIN İŞLEM İZNİ YOK",
    "0058": "POS İŞLEM TİPİNE KAPALI",
    "0059": "SAHTEKARLIK ŞÜPHESİ",
    "0061": "Para çekme tutar limiti aşıldı",
    "0062": "YASAKLANMIŞ KART",
    "0063": "Güvenlik ihlali",
    "0065": "GÜNLÜK İŞLEM ADEDİ LİMİTİ AŞILDI 0075 Şifre Deneme Sayısı Aşıldı",
    "0077": "ŞİFRE SCRIPT TALEBİ REDDEDİLDİ",
    "0078": "ŞİFRE GÜVENİLİR BULUNMADI",
    "0089": "İŞLEM ONAYLANMADI",
    "0091": "KARTI VEREN BANKA HİZMET DIŞI",
    "0092": "BANKASI BİLİNMİYOR",
    "0093": "İŞLEM ONAYLANMADI",
    "0096": "BANKASININ SİSTEMİ ARIZALI 0312 KARTIN CVV2 DEĞERİ HATALI 0315 TEKRAR DENEYİNİZ",
    "0320": "ÖNPROVİZYON KAPATILAMADI 0323 ÖNPROVİZYON KAPATILAMADI",
    "0357": "İŞLEM ONAYLANMADI",
    "0358": "Kart Kapalı",
    "0381": "RED KARTA EL KOY",
    "0382": "SAHTE KART-KARTA EL KOYUNUZ",
    "0501": "GEÇERSİZ TAKSİT/İŞLEM TUTARI",
    "0503": "KART NUMARASI HATALI",
    "0504": "İŞLEM ONAYLANMADI",
    "0540": "İade Edilecek İşlemin Orijinali Bulunamadı",
    "0541": "Orj. İşlemin tamamı iade edildi",
    "0542": "İADE İŞLEMİ GERÇEKLEŞTİRİLEMEZ",
    "0550": "İŞLEM YKB POS UNDAN YAPILMALI",
    "0570": "YURTDIŞI KART İŞLEM İZNİ YOK",
    "0571": "İşyeri Amex İşlem İzni Yok",
    "0572": "İşyeri Amex Tanımları Eksik",
    "0574": "ÜYE İŞYERİ İŞLEM İZNİ YOK",
    "0575": "İŞLEM ONAYLANMADI",
    "0577": "TAKSİTLİ İŞLEM İZNİ YOK",
    "0580": "HATALI 3D GÜVENLİK BİLGİSİ",
    "0581": "ECI veya CAVV bilgisi eksik",
    "0582": "HATALI 3D GÜVENLİK BİLGİSİ",
    "0583": "TEKRAR DENEYİNİZ",
    "0961": "İŞLEM TİPİ GEÇERSİZ",
    "0962": "TerminalID Tanımısız",
    "0963": "Üye İşyeri Tanımlı Değil",
    "0966": "İŞLEM ONAYLANMADI",
    "0971": "Eşleşmiş bir işlem iptal edilemez",
    "0972": "Para Kodu Geçersiz",
    "0973": "İŞLEM ONAYLANMADI",
    "0974": "İŞLEM ONAYLANMADI",
    "0975": "ÜYE İŞYERİ İŞLEM İZNİ YOK",
    "0976": "İŞLEM ONAYLANMADI",
    "0978": "KARTIN TAKSİTLİ İŞLEME İZNİ YOK",
    "0980": "İŞLEM ONAYLANMADI",
    "0981": "EKSİK GÜVENLİK BİLGİSİ",
    "0982": "İŞLEM İPTAL DURUMDA. İADE EDİLEMEZ",
    "0983": "İade edilemez,iptal",
    "0984": "İADE TUTAR HATASI",
    "0985": "İŞLEM ONAYLANMADI.",
    "0986": "GIB Taksit Hata",
    "0987": "İŞLEM ONAYLANMADI.",
    "8484": "Birden fazla hata olması durumunda geri dönülür. ResultDetail alanından detayları alınabilir.",
    "1001": "Sistem hatası.",
    "1006": "Bu TransactionId ile daha önce başarılı bir işlem gerçekleştirilmiş",
    "1007": "Referans Transaction alınamadı",
    "1046": "İade işleminde tutar hatalı.",
    "1047": "İşlem tutarı geçersiz.",
    "1049": "Geçersiz tutar.",
    "1050": "CVV hatalı.",
    "1051": "Kredi kartı numarası hatalı.",
    "1052": "Kredi kartı son kullanma tarihi hatalı.",
    "1054": "İşlem numarası hatalı.",
    "1059": "Yeniden iade denemesi.",
    "1060": "Hatalı taksit sayısı.",
    "2200": "İş yerinin işlem için gerekli hakkı yok.",
    "2202": "İşlem iptal edilemez. ( Batch Kapalı )",
    "5001": "İş yeri aktif değil.",
    "5002": "İş yeri şifresi yanlış.",
    "1073": "Terminal üzerinde aktif olarak bir Batch bulunamadı",
    "1074": "İşlem henüz sonlanmamış ya da referans işlem henüz tamamlanmamış.",
    "1075": "Sadakat puan tutarı hatalı",
    "1076": "Sadakat puan kodu hatalı",
    "1077": "Para kodu hatalı",
    "1078": "Geçersiz sipariş numarası",
    "1079": "Geçersiz sipariş açıklaması",
    "1080": "Sadakat tutarı ve para tutarı gönderilmemiş.",
    "1061": "Aynı sipariş numarasıyla daha önceden başarılı işlem yapılmış",
    "1065": "Ön provizyon daha önceden kapatılmış",
    "1082": "Geçersiz işlem tipi",
    "1083": "Referans işlem daha önceden iptal edilmiş.",
    "7777": "Banka tarafında gün sonu yapıldığından işlem gerçekleştirilemedi",
    "1087": "Yabancı para birimiyle taksitli provizyon kapama işlemi yapılamaz",
    "1088": "Ön provizyon iptal edilmiş",
    "1089": "Referans işlem yapılmak istenen işlem için uygun değil",
    "1090": "Bölüm numarası bulunamıyor",
    "1091": "Recurring işlemin toplam taksit sayısı hatalı",
    "1092": "Recurring işlemin tekrarlama aralığı hatalı",
    "1093": "Sadece Satış (Sale) işlemi Recurring olarak işaretlenebilir",
    "1095": "Lütfen geçerli bir Email adresi giriniz",
    "1096": "Lütfen geçerli bir IP adresi giriniz",
    "1097": "Lütfen geçerli bir CAVV değeri giriniz",
    "1098": "Lütfen geçerli bir ECI değeri giriniz.",
    "1099": "Lütfen geçerli bir Kart Sahibi ismi giriniz.",
    "1100": "Lütfen geçerli bir Brand girişi yapın.",
    "1102": "Recurring işlem aralık tipi hatalı bir değere sahip",
    "5003": "İşlem bulunamadı",
    "5004": "Kredi Kartı sağlayıcısı bulunamadı",
    "5005": "Kredi kartının ilk 6 karakteri geçersiz",
    "5006": "Hatalı kart numarası",
    "5007": "Hatalı Cvv numarası",
    "5009": "TransactionId daha önce kullanılmış",
    "5010": "Bu işlem daha önce kullanılmış",
    "5011": "Bu işlem daha önce kullanılmış",
    "5012": "Hangi sayfanın talep edildiği anlaşılamadı",
    "5013": "Geçersiz TransactionId",
    "5014": "Geçersiz işlem tutarı",
    "5015": "Geçersiz para kodu",
    "5016": "Geçersiz sipariş detay bilgisi",
    "5017": "Geçersiz sipariş numarası",
    "5018": "Eksik parametre",
    "5019": "Geçersiz parametre uzunluğu",
    "5020": "Üye işyeri numarası eksik",
    "5021": "Ödeme bileti eksik",
    "5022": "Üye iş yeri şifresi eksik",
    "5023": "Geçersiz üye iş yeri numarası",
    "5024": "Geçersiz işlem numarası uzunluğu",
    "5025": "Geçersiz sipariş numarası uzunluğu",
    "5026": "Geçersiz taksit sayısı",
    "5027": "Geçersiz işlem tipi",
    "5028": "Geçersiz işlem tipi",
    "5029": "Geçersiz istek",
    "5030": "Geçersiz HostMerchantId",
    "5031": "Geçersiz TransactionId",
    "5032": "Response değeri alınamadı",
    "5033": "Register mesajı bulunamadı",
    "5034": "Geçersiz PaymentToken",
    "5035": "TransactionId değerinde geçersiz karakter.",
    "5036": "",
    "6000": "Talep mesajı okunamadı. (Mesajda yer alan parametrelerinizin formatlarını kontrol ediniz)",
    "6969": "İşlem ACS doğrulamasından geçemedi."
}
